Ability to copy script at any time, even if the script is wrong
saving-satoshi/saving-satoshi-script pull request #18
Opened 2024-12-24 21:29 UTC by patrickReiis

First of all your project is amazing, I am recently learning Bitcoin scripts for the first time in my life.  

Anyways, the problem is that currently I can only copy after I have run the script and the script must be correct/valid, which is not ideal, sometimes I want to be able to copy the script as it is, to debug with Chat GPT, for example.  

I'm not sure about design, so I just added a simple text.

Screenshot:  
![image](https://github.com/user-attachments/assets/a0a9816f-d481-4fee-b089-299144c4f6d8)

2025-01-29 00:09 UTC, 0tuedon commented
> First of all your project is amazing, I am recently learning Bitcoin scripts for the first time in my life.
> 
> Anyways, the problem is that currently I can only copy after I have run the script and the script must be correct/valid, which is not ideal, sometimes I want to be able to copy the script as it is, to debug with Chat GPT, for example.
> 
> I'm not sure about design, so I just added a simple text.

Hi @patrickReiis , Thank you for contributing to this project, and making this PR for this issue, I will try to review this and get back to you soon.

2025-01-29 00:40 UTC, patrickReiis commented
Thanks!

2025-01-30 15:47 UTC, benalleng requested changes
I think I would prefer a different approach, see how the copy button currently works. It simply is not visible until the hasher state is in a success state, I would rather just change when the current copy button is visible to be visible on any state besides the initial empty state
https://github.com/saving-satoshi/saving-satoshi-script/blob/a1898c40919da8828722d60e3c9e99a28eefbfbc/ui/OpCodeParser/Runner/index.tsx#L117-L121

2025-01-30 19:06 UTC, patrickReiis commented
Indeed this approach is way better, fixed.

2025-01-31 01:18 UTC, benalleng approved these changes
Looks good! Thanks!

2025-01-31 01:18 UTC, merged